# Generated by Django 5.1.2 on 2024-11-18 05:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('surname', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('profile_picture', models.ImageField(blank=True, default='default/user.jpg', null=True, upload_to='users/profile_pics')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('theme', models.CharField(default='light', max_length=20)),
                ('role', models.CharField(choices=[('researcher', 'Researcher'), ('phd', 'PhD Student'), ('master', "Master's Student"), ('postdoc', 'Postdoc')], default='researcher', max_length=20)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('research_interests', models.JSONField(blank=True, null=True)),
                ('publications', models.JSONField(blank=True, null=True)),
                ('research_projects', models.JSONField(blank=True, null=True)),
                ('thesis_title', models.CharField(blank=True, max_length=255, null=True)),
                ('supervisor', models.CharField(blank=True, max_length=255, null=True)),
                ('phd_start_date', models.DateField(blank=True, null=True)),
                ('phd_end_date', models.DateField(blank=True, null=True)),
                ('academic_achievements', models.JSONField(blank=True, null=True)),
                ('awards_and_grants', models.TextField(blank=True, null=True)),
                ('publication_title', models.CharField(blank=True, max_length=255, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('publication_journal', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('personal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('notifications', models.IntegerField(default=0)),
                ('messages', models.IntegerField(default=0)),
                ('employee_id', models.IntegerField(blank=True, null=True)),
                ('admin_notes', models.JSONField(blank=True, null=True)),
                ('project_status', models.CharField(blank=True, max_length=255, null=True)),
                ('funding_source', models.CharField(blank=True, max_length=255, null=True)),
                ('grant_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='user_set_custom', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='user_permissions_custom', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
