# Generated by Django 5.1.2 on 2024-11-27 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='awards_and_grants',
        ),
    ]
