# Generated by Django 5.1.2 on 2024-11-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_awards_and_grants'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='awards',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
