# Generated by Django 5.1.2 on 2024-11-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_awards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='thesis_title',
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='USA', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='introduction',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='user',
            name='master_thesis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='thesis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('researcher', 'Researcher'), ('phd', 'PhD Student'), ('master', "Master's Student"), ('postdoc', 'Postdoc'), ('alumni', 'Alumni')], default='researcher', max_length=20),
        ),
    ]
