# Generated by Django 5.1.2 on 2024-11-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_employee_id_remove_user_thesis_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('researcher', 'Researcher'), ('principal', 'Principal'), ('undergraduate', 'Undergraduate'), ('phd', 'PhD Student'), ('master', "Master's Student"), ('postdoc', 'Postdoc'), ('alumni', 'Alumni')], default='researcher', max_length=20),
        ),
    ]
