# Generated by Django 5.1.2 on 2024-11-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('researcher', 'Researcher'), ('principal', 'Principal'), ('undergraduate', 'Undergraduate'), ('phd', 'PhD Student'), ('master', "Master's Student"), ('postdoc', 'Postdoc'), ('phdalumni', 'PhD Alumni'), ('msalumni', 'Master Alumni')], default='researcher', max_length=20),
        ),
    ]
