# Generated by Django 5.1.2 on 2025-01-03 19:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('journal', models.CharField(blank=True, max_length=255, null=True)),
                ('authors', models.TextField(blank=True, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], default='ongoing', max_length=50)),
                ('funding_source', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='publication_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='publication_journal',
        ),
        migrations.RemoveField(
            model_name='user',
            name='publication_title',
        ),
        migrations.RemoveField(
            model_name='user',
            name='academic_achievements',
        ),
        migrations.RemoveField(
            model_name='user',
            name='admin_notes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='awards',
        ),
        migrations.RemoveField(
            model_name='user',
            name='publications',
        ),
        migrations.RemoveField(
            model_name='user',
            name='research_interests',
        ),
        migrations.RemoveField(
            model_name='user',
            name='research_projects',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='admin', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='academic_achievements',
            field=models.ManyToManyField(blank=True, to='users.academicachievement'),
        ),
        migrations.AddField(
            model_name='user',
            name='admin_notes',
            field=models.ManyToManyField(blank=True, to='users.adminnote'),
        ),
        migrations.AddField(
            model_name='user',
            name='awards',
            field=models.ManyToManyField(blank=True, to='users.award'),
        ),
        migrations.AddField(
            model_name='user',
            name='publications',
            field=models.ManyToManyField(blank=True, to='users.publication'),
        ),
        migrations.AddField(
            model_name='user',
            name='research_interests',
            field=models.ManyToManyField(blank=True, to='users.researchinterest'),
        ),
        migrations.AddField(
            model_name='user',
            name='research_projects',
            field=models.ManyToManyField(blank=True, to='users.researchproject'),
        ),
    ]
