# Generated by Django 5.1.2 on 2025-01-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_academicachievement_adminnote_award_publication_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phd_end_date',
            new_name='experted_graduation',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phd_start_date',
            new_name='start_on',
        ),
        migrations.RemoveField(
            model_name='researchproject',
            name='funding_source',
        ),
        migrations.AddField(
            model_name='researchproject',
            name='keywords',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='users/cv'),
        ),
        migrations.AddField(
            model_name='user',
            name='illustrations_picture',
            field=models.ImageField(blank=True, default='default/user.jpg', null=True, upload_to='users/illustrations_pics'),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='description',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
