# Generated by Django 5.1.2 on 2025-01-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_phd_end_date_user_experted_graduation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchproject',
            name='by',
            field=models.CharField(default='israel', max_length=255),
            preserve_default=False,
        ),
    ]
