# Generated by Django 5.1.2 on 2025-01-03 21:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_researchproject_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='experted_graduation',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('researcher', 'Researcher'), ('principal', 'Principal'), ('undergraduate', 'Undergraduate'), ('phd', 'PhD Student'), ('master', "Master's Student"), ('postdoc', 'Postdoc'), ('phdalumni', 'PhD Alumni'), ('msalumni', "Master's Alumnus")], default='researcher', max_length=20),
        ),
    ]
