# Generated by Django 5.1.2 on 2025-01-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='city',
            field=models.CharField(default='Accra', max_length=255),
            preserve_default=False,
        ),
    ]
