# Generated by Django 5.1.2 on 2025-01-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_education_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='GPA',
            field=models.CharField(blank=True, max_length=224, null=True),
        ),
    ]
