# Generated by Django 5.1.2 on 2025-02-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_education_gpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(default='Software', max_length=100),
            preserve_default=False,
        ),
    ]
