# Generated by Django 5.1.2 on 2025-02-18 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_skill_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='visibility',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('Software', 'Software'), ('Hardware', 'Hardware'), ('Tools', 'Tools')], default='beginner', max_length=100),
        ),
    ]
