# Generated by Django 5.1.2 on 2025-02-18 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_publication_visibility_alter_skill_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resettokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
