# Generated by Django 5.1.2 on 2025-02-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_resettokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resettokens',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
