# Generated by Django 5.1.2 on 2025-02-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_academicachievement_user_alter_adminnote_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='careerpreparation',
            old_name='date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='careerpreparation',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
