# Generated by Django 5.1.2 on 2025-02-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_rename_date_careerpreparation_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerpreparation',
            name='institution',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
