# Generated by Django 5.1.2 on 2025-03-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_publication_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalexperience',
            name='description',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
