# Generated by Django 5.1.2 on 2025-03-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_professionalexperience_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalexperience',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='professionalexperience',
            name='country',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='professionalexperience',
            name='show_month',
            field=models.BooleanField(default=True),
        ),
    ]
