# Generated by Django 5.1.2 on 2025-03-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_professionalexperience_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='show_month',
            field=models.BooleanField(default=True),
        ),
    ]
