# Generated by Django 5.1.2 on 2024-11-18 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('dataset_file', models.FileField(blank=True, null=True, upload_to='datasets/')),
                ('publication_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ExPERT Lab', max_length=225)),
                ('logo', models.FileField(upload_to='lab')),
                ('about', models.TextField()),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
                ('values', models.TextField()),
                ('established_date', models.DateField(blank=True, help_text='Date the lab was established', null=True)),
                ('head', models.CharField(help_text="Lab head or director's name", max_length=225)),
                ('contact_email', models.EmailField(help_text='Primary contact email for the lab', max_length=254)),
                ('contact_phone', models.CharField(blank=True, help_text='Primary contact phone number', max_length=15, null=True)),
                ('location', models.CharField(help_text="Lab's physical location on campus", max_length=225)),
                ('website', models.URLField(blank=True, help_text="Lab's official website", null=True)),
                ('research_focus', models.TextField(help_text='Main research areas and focus of the lab')),
                ('affiliated_department', models.CharField(help_text='Department the lab is affiliated with', max_length=225)),
                ('publications_count', models.PositiveIntegerField(default=0, help_text='Number of publications produced by the lab')),
                ('equipment', models.TextField(blank=True, help_text='List of major equipment or facilities available in the lab', null=True)),
                ('funding_sources', models.CharField(blank=True, help_text='Primary sources of funding', max_length=500, null=True)),
                ('team_members', models.TextField(blank=True, help_text='Key team members and their roles', null=True)),
                ('social_media_links', models.JSONField(blank=True, help_text="Social media links as JSON (e.g., {'twitter': 'link', 'linkedin': 'link'})", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=255)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('authors', models.CharField(max_length=225)),
                ('journal', models.CharField(blank=True, max_length=255, null=True)),
                ('publication_date', models.DateField()),
                ('doi', models.CharField(blank=True, max_length=100, null=True)),
                ('abstract', models.TextField()),
                ('pdf', models.FileField(blank=True, null=True, upload_to='publications/')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the slider item', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description or caption for the slider item', null=True)),
                ('image', models.ImageField(help_text='Image for the slider item', upload_to='slider')),
                ('link', models.URLField(blank=True, help_text='Optional link associated with the slider item', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the sponsor', max_length=255)),
                ('logo', models.ImageField(help_text='Logo of the sponsor', upload_to='sponsors_logos')),
                ('website', models.URLField(blank=True, help_text="Sponsor's website URL", null=True)),
                ('description', models.TextField(blank=True, help_text='Brief description about the sponsor', null=True)),
                ('support_level', models.CharField(blank=True, help_text='Level of sponsorship (e.g., Platinum, Gold)', max_length=100, null=True)),
                ('added_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('lead_researcher', models.TextField(null=True)),
                ('collaborators', models.JSONField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=100)),
                ('funding_agency', models.CharField(blank=True, max_length=255, null=True)),
                ('funding_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('outcomes', models.TextField(blank=True, null=True)),
                ('publications', models.ManyToManyField(blank=True, to='main.publication')),
                ('related_datasets', models.ManyToManyField(blank=True, to='main.database')),
            ],
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='highlights/')),
                ('related_publications', models.ManyToManyField(blank=True, to='main.publication')),
                ('related_research', models.ManyToManyField(blank=True, to='main.research')),
            ],
        ),
        migrations.AddField(
            model_name='database',
            name='related_research',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.research'),
        ),
        migrations.CreateModel(
            name='Teaching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('instructor', models.CharField(max_length=225)),
                ('semester', models.CharField(max_length=20)),
                ('syllabus', models.TextField()),
                ('materials', models.FileField(blank=True, null=True, upload_to='teaching/materials/')),
                ('related_research', models.ManyToManyField(blank=True, to='main.research')),
            ],
        ),
    ]
