# Generated by Django 5.1.2 on 2024-11-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='align',
            field=models.TextField(default='left'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slider',
            name='link',
            field=models.CharField(blank=True, help_text='Optional link associated with the slider item', max_length=225, null=True),
        ),
    ]
