# Generated by Django 5.1.2 on 2024-11-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_slider_align_alter_slider_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(blank=True, help_text='Title of the slider item', max_length=255, null=True),
        ),
    ]
