# Generated by Django 5.1.2 on 2024-11-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_slider_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='display_title',
            field=models.BooleanField(default=True),
        ),
    ]
