# Generated by Django 5.1.2 on 2024-11-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_slider_display_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.ImageField(help_text='Logo of the sponsor', upload_to='sponsors'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='website',
            field=models.TextField(blank=True, help_text="Sponsor's website URL", null=True),
        ),
    ]
