# Generated by Django 5.1.2 on 2025-01-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_sponsor_logo_alter_sponsor_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='index',
            field=models.IntegerField(default=0, verbose_name='Order number'),
            preserve_default=False,
        ),
    ]
