# Generated by Django 5.1.2 on 2025-01-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_slider_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='index',
            field=models.IntegerField(default=1, verbose_name='Order Number In cardinal'),
            preserve_default=False,
        ),
    ]
