# Generated by Django 5.1.2 on 2025-02-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_sponsor_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='doi',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='journal',
        ),
        migrations.AddField(
            model_name='publication',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
