# Generated by Django 5.1.2 on 2025-02-24 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_publication_authors_remove_publication_doi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='publications',
        ),
        migrations.RemoveField(
            model_name='research',
            name='related_datasets',
        ),
        migrations.RemoveField(
            model_name='teaching',
            name='related_research',
        ),
        migrations.DeleteModel(
            name='Highlight',
        ),
    ]
