# Generated by Django 5.1.2 on 2025-02-24 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_research_publications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='publication_date',
        ),
        migrations.RemoveField(
            model_name='database',
            name='related_research',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='publications_count',
        ),
    ]
