# Generated by Django 5.1.2 on 2025-02-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_database_publication_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='bullet_points',
            field=models.JSONField(default=[], null=True),
        ),
    ]
