# Generated by Django 5.1.2 on 2025-02-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_research_bullet_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='bullet_points',
            field=models.JSONField(default=list, null=True),
        ),
    ]
