# Generated by Django 5.1.2 on 2025-02-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_research_bullet_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='collaborators',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='research',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='research',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
