# Generated by Django 5.1.2 on 2025-02-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_research_collaborators_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='pic',
            field=models.ImageField(default='/static/main/img/pubbg.jpg', null=True, upload_to='main/researchs'),
        ),
    ]
