# Generated by Django 5.1.2 on 2025-02-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_research_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='pic',
            field=models.ImageField(default='/pubbg.jpg', null=True, upload_to='main/researchs'),
        ),
    ]
