# Generated by Django 5.1.2 on 2025-03-13 10:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_research_pic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-publication_date']},
        ),
        migrations.RenameField(
            model_name='news',
            old_name='content',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='published_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='news',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('publication', 'Publication'), ('event', 'Event'), ('grant', 'Grant/Funding'), ('achievement', 'Achievement'), ('collaboration', 'Collaboration')], default='publication', max_length=20),
        ),
        migrations.AddField(
            model_name='news',
            name='conclusion',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='featured_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='news/image1/'),
        ),
        migrations.AddField(
            model_name='news',
            name='featured_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='news/image2/'),
        ),
        migrations.AddField(
            model_name='news',
            name='featured_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='news/image3/'),
        ),
        migrations.AddField(
            model_name='news',
            name='featured_video',
            field=models.ImageField(blank=True, null=True, upload_to='news/video/'),
        ),
        migrations.AddField(
            model_name='news',
            name='intro',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='newstags',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='publication_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='news',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
