# Generated by Django 5.1.2 on 2025-03-13 10:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_news_options_rename_content_news_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('intro', models.TextField()),
                ('body', models.TextField()),
                ('conclusion', models.TextField()),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(max_length=255)),
                ('featured_image_1', models.ImageField(blank=True, null=True, upload_to='news/image1/')),
                ('featured_image_2', models.ImageField(blank=True, null=True, upload_to='news/image2/')),
                ('featured_image_3', models.ImageField(blank=True, null=True, upload_to='news/image3/')),
                ('featured_video', models.ImageField(blank=True, null=True, upload_to='news/video/')),
                ('category', models.CharField(choices=[('publication', 'Publication'), ('event', 'Event'), ('grant', 'Grant/Funding'), ('achievement', 'Achievement'), ('collaboration', 'Collaboration')], default='publication', max_length=20)),
                ('newstags', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'ordering': ['-publication_date'],
            },
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
