# Generated by Django 5.1.2 on 2025-03-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_new_delete_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='featured_video',
            field=models.FileField(blank=True, null=True, upload_to='news/video/'),
        ),
    ]
