# Generated by Django 5.1.2 on 2025-03-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_new_featured_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='number_of_times_read',
            field=models.IntegerField(default=1),
        ),
    ]
