# Generated by Django 5.1.2 on 2025-03-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_newscomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscomment',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
